//
//  ZJHGameNotification.h
//  Draw
//
//  Created by 王 小涛 on 12-10-29.
//
//

#ifndef Draw_ZJHGameNotification_h
#define Draw_ZJHGameNotification_h

#define NOTIFICATION_BET_REQUEST @"NOTIFICATION_BET_REQUEST"
#define NOTIFICATION_BET_RESPONSE @"NOTIFICATION_BET_RESPONSE"

#define NOTIFICATION_CHECK_CARD_REQUEST @"NOTIFICATION_CHECK_CARD_REQUEST"
#define NOTIFICATION_CHECK_CARD_RESPONSE @"NOTIFICATION_CHECK_CARD_RESPONSE"

#define NOTIFICATION_FOLD_CARD_REQUEST @"NOTIFICATION_FOLD_CARD_REQUEST"
#define NOTIFICATION_FOLD_CARD_RESPONSE @"NOTIFICATION_FOLD_CARD_RESPONSE"

#define NOTIFICATION_SHOW_CARD_REQUEST @"NOTIFICATION_SHOW_CARD_REQUEST"
#define NOTIFICATION_SHOW_CARD_RESPONSE @"NOTIFICATION_SHOW_CARD_RESPONSE"

#define NOTIFICATION_COMPARE_CARD_REQUEST @"NOTIFICATION_COMPARE_CARD_REQUEST"
#define NOTIFICATION_COMPARE_CARD_RESPONSE @"NOTIFICATION_COMPARE_CARD_RESPONSE"

#define NOTIFICATION_CHANGE_CARD_REQUEST @"NOTIFICATION_CHANGE_CARD_REQUEST"
#define NOTIFICATION_CHANGE_CARD_RESPONSE @"NOTIFICATION_CHANGE_CARD_RESPONSE"


#endif
