//
//  DiceNotification.h
//  Draw
//
//  Created by  on 12-8-4.
//  Copyright (c) 2012年 __MyCompanyName__. All rights reserved.
//

#define NOTIFICATION_ROLL_DICE_BEGIN            @"NOTIFICATION_ROLL_DICE_BEGIN"
#define NOTIFICATION_ROLL_DICE_END              @"NOTIFICATION_ROLL_DICE_END"
#define NOTIFICATION_NEXT_PLAYER_START          @"NOTIFICATION_NEXT_PLAYER_START"
#define NOTIFICATION_CALL_DICE_REQUEST          @"NOTIFICATION_CALL_DICE_REQUEST"
#define NOTIFICATION_OPEN_DICE_REQUEST          @"NOTIFICATION_OPEN_DICE_REQUEST"
#define NOTIFICATION_OPEN_DICE_RESPONSE         @"NOTIFICATION_OPEN_DICE_RESPONSE"
#define NOTIFICAIION_CREATE_ROOM_RESPONSE       @"NOTIFICAIION_CREATE_ROOM_RESPONSE"

