/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "BBS.pb-c.h"
void   game__pbbbsuser__init
                     (Game__PBBBSUser         *message)
{
  static Game__PBBBSUser init_value = GAME__PBBBSUSER__INIT;
  *message = init_value;
}
size_t game__pbbbsuser__get_packed_size
                     (const Game__PBBBSUser *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsuser__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsuser__pack
                     (const Game__PBBBSUser *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsuser__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsuser__pack_to_buffer
                     (const Game__PBBBSUser *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsuser__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSUser *
       game__pbbbsuser__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSUser *)
     protobuf_c_message_unpack (&game__pbbbsuser__descriptor,
                                allocator, len, data);
}
void   game__pbbbsuser__free_unpacked
                     (Game__PBBBSUser *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsuser__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsdraw__init
                     (Game__PBBBSDraw         *message)
{
  static Game__PBBBSDraw init_value = GAME__PBBBSDRAW__INIT;
  *message = init_value;
}
size_t game__pbbbsdraw__get_packed_size
                     (const Game__PBBBSDraw *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsdraw__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsdraw__pack
                     (const Game__PBBBSDraw *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsdraw__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsdraw__pack_to_buffer
                     (const Game__PBBBSDraw *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsdraw__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSDraw *
       game__pbbbsdraw__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSDraw *)
     protobuf_c_message_unpack (&game__pbbbsdraw__descriptor,
                                allocator, len, data);
}
void   game__pbbbsdraw__free_unpacked
                     (Game__PBBBSDraw *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsdraw__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbscontent__init
                     (Game__PBBBSContent         *message)
{
  static Game__PBBBSContent init_value = GAME__PBBBSCONTENT__INIT;
  *message = init_value;
}
size_t game__pbbbscontent__get_packed_size
                     (const Game__PBBBSContent *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbscontent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbscontent__pack
                     (const Game__PBBBSContent *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbscontent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbscontent__pack_to_buffer
                     (const Game__PBBBSContent *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbscontent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSContent *
       game__pbbbscontent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSContent *)
     protobuf_c_message_unpack (&game__pbbbscontent__descriptor,
                                allocator, len, data);
}
void   game__pbbbscontent__free_unpacked
                     (Game__PBBBSContent *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbscontent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsreward__init
                     (Game__PBBBSReward         *message)
{
  static Game__PBBBSReward init_value = GAME__PBBBSREWARD__INIT;
  *message = init_value;
}
size_t game__pbbbsreward__get_packed_size
                     (const Game__PBBBSReward *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsreward__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsreward__pack
                     (const Game__PBBBSReward *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsreward__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsreward__pack_to_buffer
                     (const Game__PBBBSReward *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsreward__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSReward *
       game__pbbbsreward__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSReward *)
     protobuf_c_message_unpack (&game__pbbbsreward__descriptor,
                                allocator, len, data);
}
void   game__pbbbsreward__free_unpacked
                     (Game__PBBBSReward *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsreward__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbspost__init
                     (Game__PBBBSPost         *message)
{
  static Game__PBBBSPost init_value = GAME__PBBBSPOST__INIT;
  *message = init_value;
}
size_t game__pbbbspost__get_packed_size
                     (const Game__PBBBSPost *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbspost__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbspost__pack
                     (const Game__PBBBSPost *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbspost__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbspost__pack_to_buffer
                     (const Game__PBBBSPost *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbspost__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSPost *
       game__pbbbspost__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSPost *)
     protobuf_c_message_unpack (&game__pbbbspost__descriptor,
                                allocator, len, data);
}
void   game__pbbbspost__free_unpacked
                     (Game__PBBBSPost *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbspost__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsprivilege__init
                     (Game__PBBBSPrivilege         *message)
{
  static Game__PBBBSPrivilege init_value = GAME__PBBBSPRIVILEGE__INIT;
  *message = init_value;
}
size_t game__pbbbsprivilege__get_packed_size
                     (const Game__PBBBSPrivilege *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsprivilege__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsprivilege__pack
                     (const Game__PBBBSPrivilege *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsprivilege__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsprivilege__pack_to_buffer
                     (const Game__PBBBSPrivilege *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsprivilege__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSPrivilege *
       game__pbbbsprivilege__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSPrivilege *)
     protobuf_c_message_unpack (&game__pbbbsprivilege__descriptor,
                                allocator, len, data);
}
void   game__pbbbsprivilege__free_unpacked
                     (Game__PBBBSPrivilege *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsprivilege__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsaction_source__init
                     (Game__PBBBSActionSource         *message)
{
  static Game__PBBBSActionSource init_value = GAME__PBBBSACTION_SOURCE__INIT;
  *message = init_value;
}
size_t game__pbbbsaction_source__get_packed_size
                     (const Game__PBBBSActionSource *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction_source__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsaction_source__pack
                     (const Game__PBBBSActionSource *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction_source__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsaction_source__pack_to_buffer
                     (const Game__PBBBSActionSource *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction_source__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSActionSource *
       game__pbbbsaction_source__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSActionSource *)
     protobuf_c_message_unpack (&game__pbbbsaction_source__descriptor,
                                allocator, len, data);
}
void   game__pbbbsaction_source__free_unpacked
                     (Game__PBBBSActionSource *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction_source__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsaction__init
                     (Game__PBBBSAction         *message)
{
  static Game__PBBBSAction init_value = GAME__PBBBSACTION__INIT;
  *message = init_value;
}
size_t game__pbbbsaction__get_packed_size
                     (const Game__PBBBSAction *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsaction__pack
                     (const Game__PBBBSAction *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsaction__pack_to_buffer
                     (const Game__PBBBSAction *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSAction *
       game__pbbbsaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSAction *)
     protobuf_c_message_unpack (&game__pbbbsaction__descriptor,
                                allocator, len, data);
}
void   game__pbbbsaction__free_unpacked
                     (Game__PBBBSAction *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbbbsboard__init
                     (Game__PBBBSBoard         *message)
{
  static Game__PBBBSBoard init_value = GAME__PBBBSBOARD__INIT;
  *message = init_value;
}
size_t game__pbbbsboard__get_packed_size
                     (const Game__PBBBSBoard *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsboard__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbbbsboard__pack
                     (const Game__PBBBSBoard *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsboard__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbbbsboard__pack_to_buffer
                     (const Game__PBBBSBoard *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsboard__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBBBSBoard *
       game__pbbbsboard__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBBBSBoard *)
     protobuf_c_message_unpack (&game__pbbbsboard__descriptor,
                                allocator, len, data);
}
void   game__pbbbsboard__free_unpacked
                     (Game__PBBBSBoard *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbbbsboard__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor game__pbbbsuser__field_descriptors[4] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSUser, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "nickName",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSUser, nickname),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "avatar",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSUser, avatar),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gender",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Game__PBBBSUser, has_gender),
    PROTOBUF_C_OFFSETOF(Game__PBBBSUser, gender),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsuser__field_indices_by_name[] = {
  2,   /* field[2] = avatar */
  3,   /* field[3] = gender */
  1,   /* field[1] = nickName */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange game__pbbbsuser__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor game__pbbbsuser__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSUser",
  "PBBBSUser",
  "Game__PBBBSUser",
  "game",
  sizeof(Game__PBBBSUser),
  4,
  game__pbbbsuser__field_descriptors,
  game__pbbbsuser__field_indices_by_name,
  1,  game__pbbbsuser__number_ranges,
  (ProtobufCMessageInit) game__pbbbsuser__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t game__pbbbsdraw__version__default_value = 0;
static const ProtobufCFieldDescriptor game__pbbbsdraw__field_descriptors[3] =
{
  {
    "drawActionList",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBBBSDraw, n_drawactionlist),
    PROTOBUF_C_OFFSETOF(Game__PBBBSDraw, drawactionlist),
    &game__pbdraw_action__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBBBSDraw, has_version),
    PROTOBUF_C_OFFSETOF(Game__PBBBSDraw, version),
    NULL,
    &game__pbbbsdraw__version__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "canvasSize",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSDraw, canvassize),
    &game__pbsize__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsdraw__field_indices_by_name[] = {
  2,   /* field[2] = canvasSize */
  0,   /* field[0] = drawActionList */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange game__pbbbsdraw__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__pbbbsdraw__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSDraw",
  "PBBBSDraw",
  "Game__PBBBSDraw",
  "game",
  sizeof(Game__PBBBSDraw),
  3,
  game__pbbbsdraw__field_descriptors,
  game__pbbbsdraw__field_indices_by_name,
  1,  game__pbbbsdraw__number_ranges,
  (ProtobufCMessageInit) game__pbbbsdraw__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbscontent__field_descriptors[7] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "text",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, text),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thumbImageUrl",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, thumbimageurl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "imageUrl",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, imageurl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drawThumbUrl",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, drawthumburl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drawImageUrl",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, drawimageurl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drawData",
    22,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSContent, drawdata),
    &game__pbbbsdraw__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbscontent__field_indices_by_name[] = {
  6,   /* field[6] = drawData */
  5,   /* field[5] = drawImageUrl */
  4,   /* field[4] = drawThumbUrl */
  3,   /* field[3] = imageUrl */
  1,   /* field[1] = text */
  2,   /* field[2] = thumbImageUrl */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange game__pbbbscontent__number_ranges[3 + 1] =
{
  { 1, 0 },
  { 10, 2 },
  { 20, 4 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor game__pbbbscontent__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSContent",
  "PBBBSContent",
  "Game__PBBBSContent",
  "game",
  sizeof(Game__PBBBSContent),
  7,
  game__pbbbscontent__field_descriptors,
  game__pbbbscontent__field_indices_by_name,
  3,  game__pbbbscontent__number_ranges,
  (ProtobufCMessageInit) game__pbbbscontent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbsreward__field_descriptors[5] =
{
  {
    "bonus",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, bonus),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "winner",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, winner),
    &game__pbbbsuser__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "awardDate",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, has_awarddate),
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, awarddate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionId",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSReward, actionid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsreward__field_indices_by_name[] = {
  4,   /* field[4] = actionId */
  3,   /* field[3] = awardDate */
  0,   /* field[0] = bonus */
  1,   /* field[1] = status */
  2,   /* field[2] = winner */
};
static const ProtobufCIntRange game__pbbbsreward__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor game__pbbbsreward__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSReward",
  "PBBBSReward",
  "Game__PBBBSReward",
  "game",
  sizeof(Game__PBBBSReward),
  5,
  game__pbbbsreward__field_descriptors,
  game__pbbbsreward__field_indices_by_name,
  1,  game__pbbbsreward__number_ranges,
  (ProtobufCMessageInit) game__pbbbsreward__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbspost__field_descriptors[13] =
{
  {
    "postId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, postid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boardId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, boardid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appId",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, appid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceType",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, devicetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replyCount",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, replycount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "supportCount",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, supportcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, createdate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "modifyDate",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, modifydate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createUser",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, createuser),
    &game__pbbbsuser__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, content),
    &game__pbbbscontent__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reward",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, reward),
    &game__pbbbsreward__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, has_status),
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "boardAdminList",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, n_boardadminlist),
    PROTOBUF_C_OFFSETOF(Game__PBBBSPost, boardadminlist),
    &game__pbbbsuser__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbspost__field_indices_by_name[] = {
  2,   /* field[2] = appId */
  12,   /* field[12] = boardAdminList */
  1,   /* field[1] = boardId */
  9,   /* field[9] = content */
  6,   /* field[6] = createDate */
  8,   /* field[8] = createUser */
  3,   /* field[3] = deviceType */
  7,   /* field[7] = modifyDate */
  0,   /* field[0] = postId */
  4,   /* field[4] = replyCount */
  10,   /* field[10] = reward */
  11,   /* field[11] = status */
  5,   /* field[5] = supportCount */
};
static const ProtobufCIntRange game__pbbbspost__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor game__pbbbspost__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSPost",
  "PBBBSPost",
  "Game__PBBBSPost",
  "game",
  sizeof(Game__PBBBSPost),
  13,
  game__pbbbspost__field_descriptors,
  game__pbbbspost__field_indices_by_name,
  1,  game__pbbbspost__number_ranges,
  (ProtobufCMessageInit) game__pbbbspost__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbsprivilege__field_descriptors[2] =
{
  {
    "boardId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPrivilege, boardid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "permission",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSPrivilege, permission),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsprivilege__field_indices_by_name[] = {
  0,   /* field[0] = boardId */
  1,   /* field[1] = permission */
};
static const ProtobufCIntRange game__pbbbsprivilege__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__pbbbsprivilege__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSPrivilege",
  "PBBBSPrivilege",
  "Game__PBBBSPrivilege",
  "game",
  sizeof(Game__PBBBSPrivilege),
  2,
  game__pbbbsprivilege__field_descriptors,
  game__pbbbsprivilege__field_indices_by_name,
  1,  game__pbbbsprivilege__number_ranges,
  (ProtobufCMessageInit) game__pbbbsprivilege__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbsaction_source__field_descriptors[7] =
{
  {
    "postId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, postid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postUid",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, postuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionId",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, actionid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionUid",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, actionuid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionNick",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, actionnick),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionType",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, has_actiontype),
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, actiontype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "briefText",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSActionSource, brieftext),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsaction_source__field_indices_by_name[] = {
  2,   /* field[2] = actionId */
  4,   /* field[4] = actionNick */
  5,   /* field[5] = actionType */
  3,   /* field[3] = actionUid */
  6,   /* field[6] = briefText */
  0,   /* field[0] = postId */
  1,   /* field[1] = postUid */
};
static const ProtobufCIntRange game__pbbbsaction_source__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor game__pbbbsaction_source__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSActionSource",
  "PBBBSActionSource",
  "Game__PBBBSActionSource",
  "game",
  sizeof(Game__PBBBSActionSource),
  7,
  game__pbbbsaction_source__field_descriptors,
  game__pbbbsaction_source__field_indices_by_name,
  1,  game__pbbbsaction_source__number_ranges,
  (ProtobufCMessageInit) game__pbbbsaction_source__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbsaction__field_descriptors[8] =
{
  {
    "actionId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, actionid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createUser",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, createuser),
    &game__pbbbsuser__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceType",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, devicetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, createdate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "replyCount",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, has_replycount),
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, replycount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "content",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, content),
    &game__pbbbscontent__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSAction, source),
    &game__pbbbsaction_source__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsaction__field_indices_by_name[] = {
  0,   /* field[0] = actionId */
  6,   /* field[6] = content */
  4,   /* field[4] = createDate */
  2,   /* field[2] = createUser */
  3,   /* field[3] = deviceType */
  5,   /* field[5] = replyCount */
  7,   /* field[7] = source */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange game__pbbbsaction__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 5, 3 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor game__pbbbsaction__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSAction",
  "PBBBSAction",
  "Game__PBBBSAction",
  "game",
  sizeof(Game__PBBBSAction),
  8,
  game__pbbbsaction__field_descriptors,
  game__pbbbsaction__field_indices_by_name,
  2,  game__pbbbsaction__number_ranges,
  (ProtobufCMessageInit) game__pbbbsaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbbbsboard__field_descriptors[10] =
{
  {
    "boardId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, boardid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "icon",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, icon),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionCount",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, actioncount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "postCount",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, postcount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parentBoardId",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, parentboardid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastPost",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, lastpost),
    &game__pbbbspost__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "desc",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, desc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "adminList",
    10,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, n_adminlist),
    PROTOBUF_C_OFFSETOF(Game__PBBBSBoard, adminlist),
    &game__pbbbsuser__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbbbsboard__field_indices_by_name[] = {
  4,   /* field[4] = actionCount */
  9,   /* field[9] = adminList */
  0,   /* field[0] = boardId */
  8,   /* field[8] = desc */
  3,   /* field[3] = icon */
  7,   /* field[7] = lastPost */
  2,   /* field[2] = name */
  6,   /* field[6] = parentBoardId */
  5,   /* field[5] = postCount */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange game__pbbbsboard__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor game__pbbbsboard__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBBBSBoard",
  "PBBBSBoard",
  "Game__PBBBSBoard",
  "game",
  sizeof(Game__PBBBSBoard),
  10,
  game__pbbbsboard__field_descriptors,
  game__pbbbsboard__field_indices_by_name,
  1,  game__pbbbsboard__number_ranges,
  (ProtobufCMessageInit) game__pbbbsboard__init,
  NULL,NULL,NULL    /* reserved[123] */
};
