/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "Dice.pb-c.h"
void   game__pbdice__init
                     (Game__PBDice         *message)
{
  static Game__PBDice init_value = GAME__PBDICE__INIT;
  *message = init_value;
}
size_t game__pbdice__get_packed_size
                     (const Game__PBDice *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbdice__pack
                     (const Game__PBDice *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbdice__pack_to_buffer
                     (const Game__PBDice *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBDice *
       game__pbdice__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBDice *)
     protobuf_c_message_unpack (&game__pbdice__descriptor,
                                allocator, len, data);
}
void   game__pbdice__free_unpacked
                     (Game__PBDice *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbuser_dice__init
                     (Game__PBUserDice         *message)
{
  static Game__PBUserDice init_value = GAME__PBUSER_DICE__INIT;
  *message = init_value;
}
size_t game__pbuser_dice__get_packed_size
                     (const Game__PBUserDice *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_dice__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbuser_dice__pack
                     (const Game__PBUserDice *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_dice__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbuser_dice__pack_to_buffer
                     (const Game__PBUserDice *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_dice__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBUserDice *
       game__pbuser_dice__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBUserDice *)
     protobuf_c_message_unpack (&game__pbuser_dice__descriptor,
                                allocator, len, data);
}
void   game__pbuser_dice__free_unpacked
                     (Game__PBUserDice *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_dice__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbdice_final_count__init
                     (Game__PBDiceFinalCount         *message)
{
  static Game__PBDiceFinalCount init_value = GAME__PBDICE_FINAL_COUNT__INIT;
  *message = init_value;
}
size_t game__pbdice_final_count__get_packed_size
                     (const Game__PBDiceFinalCount *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_final_count__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbdice_final_count__pack
                     (const Game__PBDiceFinalCount *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_final_count__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbdice_final_count__pack_to_buffer
                     (const Game__PBDiceFinalCount *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_final_count__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBDiceFinalCount *
       game__pbdice_final_count__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBDiceFinalCount *)
     protobuf_c_message_unpack (&game__pbdice_final_count__descriptor,
                                allocator, len, data);
}
void   game__pbdice_final_count__free_unpacked
                     (Game__PBDiceFinalCount *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_final_count__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbdice_game_result__init
                     (Game__PBDiceGameResult         *message)
{
  static Game__PBDiceGameResult init_value = GAME__PBDICE_GAME_RESULT__INIT;
  *message = init_value;
}
size_t game__pbdice_game_result__get_packed_size
                     (const Game__PBDiceGameResult *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_game_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbdice_game_result__pack
                     (const Game__PBDiceGameResult *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_game_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbdice_game_result__pack_to_buffer
                     (const Game__PBDiceGameResult *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_game_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBDiceGameResult *
       game__pbdice_game_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBDiceGameResult *)
     protobuf_c_message_unpack (&game__pbdice_game_result__descriptor,
                                allocator, len, data);
}
void   game__pbdice_game_result__free_unpacked
                     (Game__PBDiceGameResult *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_game_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbdice_action__init
                     (Game__PBDiceAction         *message)
{
  static Game__PBDiceAction init_value = GAME__PBDICE_ACTION__INIT;
  *message = init_value;
}
size_t game__pbdice_action__get_packed_size
                     (const Game__PBDiceAction *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbdice_action__pack
                     (const Game__PBDiceAction *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbdice_action__pack_to_buffer
                     (const Game__PBDiceAction *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBDiceAction *
       game__pbdice_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBDiceAction *)
     protobuf_c_message_unpack (&game__pbdice_action__descriptor,
                                allocator, len, data);
}
void   game__pbdice_action__free_unpacked
                     (Game__PBDiceAction *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbdice_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor game__pbdice__field_descriptors[2] =
{
  {
    "diceId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBDice, has_diceid),
    PROTOBUF_C_OFFSETOF(Game__PBDice, diceid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dice",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBDice, dice),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbdice__field_indices_by_name[] = {
  1,   /* field[1] = dice */
  0,   /* field[0] = diceId */
};
static const ProtobufCIntRange game__pbdice__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__pbdice__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBDice",
  "PBDice",
  "Game__PBDice",
  "game",
  sizeof(Game__PBDice),
  2,
  game__pbdice__field_descriptors,
  game__pbdice__field_indices_by_name,
  1,  game__pbdice__number_ranges,
  (ProtobufCMessageInit) game__pbdice__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const Game__PBDiceType game__pbuser_dice__type__default_value = GAME__PBDICE_TYPE__DICE_NORMAL;
static const ProtobufCFieldDescriptor game__pbuser_dice__field_descriptors[3] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserDice, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dices",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBUserDice, n_dices),
    PROTOBUF_C_OFFSETOF(Game__PBUserDice, dices),
    &game__pbdice__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Game__PBUserDice, has_type),
    PROTOBUF_C_OFFSETOF(Game__PBUserDice, type),
    &game__pbdice_type__descriptor,
    &game__pbuser_dice__type__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbuser_dice__field_indices_by_name[] = {
  1,   /* field[1] = dices */
  2,   /* field[2] = type */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange game__pbuser_dice__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__pbuser_dice__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBUserDice",
  "PBUserDice",
  "Game__PBUserDice",
  "game",
  sizeof(Game__PBUserDice),
  3,
  game__pbuser_dice__field_descriptors,
  game__pbuser_dice__field_indices_by_name,
  1,  game__pbuser_dice__number_ranges,
  (ProtobufCMessageInit) game__pbuser_dice__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const Game__PBDiceType game__pbdice_final_count__type__default_value = GAME__PBDICE_TYPE__DICE_NORMAL;
static const ProtobufCFieldDescriptor game__pbdice_final_count__field_descriptors[3] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBDiceFinalCount, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBDiceFinalCount, type),
    &game__pbdice_type__descriptor,
    &game__pbdice_final_count__type__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finalDiceCount",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBDiceFinalCount, finaldicecount),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbdice_final_count__field_indices_by_name[] = {
  2,   /* field[2] = finalDiceCount */
  1,   /* field[1] = type */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange game__pbdice_final_count__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__pbdice_final_count__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBDiceFinalCount",
  "PBDiceFinalCount",
  "Game__PBDiceFinalCount",
  "game",
  sizeof(Game__PBDiceFinalCount),
  3,
  game__pbdice_final_count__field_descriptors,
  game__pbdice_final_count__field_indices_by_name,
  1,  game__pbdice_final_count__number_ranges,
  (ProtobufCMessageInit) game__pbdice_final_count__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t game__pbdice_game_result__open_type__default_value = 0;
static const ProtobufCFieldDescriptor game__pbdice_game_result__field_descriptors[3] =
{
  {
    "userResult",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, n_userresult),
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, userresult),
    &game__pbuser_result__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "openType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, has_opentype),
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, opentype),
    NULL,
    &game__pbdice_game_result__open_type__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "finalCount",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, n_finalcount),
    PROTOBUF_C_OFFSETOF(Game__PBDiceGameResult, finalcount),
    &game__pbdice_final_count__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbdice_game_result__field_indices_by_name[] = {
  2,   /* field[2] = finalCount */
  1,   /* field[1] = openType */
  0,   /* field[0] = userResult */
};
static const ProtobufCIntRange game__pbdice_game_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__pbdice_game_result__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBDiceGameResult",
  "PBDiceGameResult",
  "Game__PBDiceGameResult",
  "game",
  sizeof(Game__PBDiceGameResult),
  3,
  game__pbdice_game_result__field_descriptors,
  game__pbdice_game_result__field_indices_by_name,
  1,  game__pbdice_game_result__number_ranges,
  (ProtobufCMessageInit) game__pbdice_game_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean game__pbdice_action__wilds__default_value = 0;
static const ProtobufCFieldDescriptor game__pbdice_action__field_descriptors[4] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, has_num),
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, num),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dice",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, has_dice),
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, dice),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "wilds",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, has_wilds),
    PROTOBUF_C_OFFSETOF(Game__PBDiceAction, wilds),
    NULL,
    &game__pbdice_action__wilds__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbdice_action__field_indices_by_name[] = {
  2,   /* field[2] = dice */
  1,   /* field[1] = num */
  0,   /* field[0] = type */
  3,   /* field[3] = wilds */
};
static const ProtobufCIntRange game__pbdice_action__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor game__pbdice_action__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBDiceAction",
  "PBDiceAction",
  "Game__PBDiceAction",
  "game",
  sizeof(Game__PBDiceAction),
  4,
  game__pbdice_action__field_descriptors,
  game__pbdice_action__field_indices_by_name,
  1,  game__pbdice_action__number_ranges,
  (ProtobufCMessageInit) game__pbdice_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue game__pbdice_type__enum_values_by_number[4] =
{
  { "DICE_NORMAL", "GAME__PBDICE_TYPE__DICE_NORMAL", 0 },
  { "DICE_SNAKE", "GAME__PBDICE_TYPE__DICE_SNAKE", 1 },
  { "DICE_NET", "GAME__PBDICE_TYPE__DICE_NET", 2 },
  { "DICE_WAI", "GAME__PBDICE_TYPE__DICE_WAI", 3 },
};
static const ProtobufCIntRange game__pbdice_type__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex game__pbdice_type__enum_values_by_name[4] =
{
  { "DICE_NET", 2 },
  { "DICE_NORMAL", 0 },
  { "DICE_SNAKE", 1 },
  { "DICE_WAI", 3 },
};
const ProtobufCEnumDescriptor game__pbdice_type__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "game.PBDiceType",
  "PBDiceType",
  "Game__PBDiceType",
  "game",
  4,
  game__pbdice_type__enum_values_by_number,
  4,
  game__pbdice_type__enum_values_by_name,
  1,
  game__pbdice_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
