/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_GameBasic_2eproto__INCLUDED
#define PROTOBUF_C_GameBasic_2eproto__INCLUDED

#include "protobuf-c.h"

PROTOBUF_C_BEGIN_DECLS


typedef struct _Game__PBKeyValue Game__PBKeyValue;
typedef struct _Game__PBSNSUser Game__PBSNSUser;
typedef struct _Game__PBUserLevel Game__PBUserLevel;
typedef struct _Game__PBGameUser Game__PBGameUser;
typedef struct _Game__PBGameSession Game__PBGameSession;
typedef struct _Game__PBGameSessionChanged Game__PBGameSessionChanged;
typedef struct _Game__PBDrawBg Game__PBDrawBg;
typedef struct _Game__PBSettingInfo Game__PBSettingInfo;
typedef struct _Game__PBDrawAction Game__PBDrawAction;
typedef struct _Game__PBMessage Game__PBMessage;
typedef struct _Game__PBMessageStat Game__PBMessageStat;
typedef struct _Game__PBUserBasicInfo Game__PBUserBasicInfo;
typedef struct _Game__PBUserResult Game__PBUserResult;
typedef struct _Game__PBItemPriceInfo Game__PBItemPriceInfo;
typedef struct _Game__PBPromotionInfo Game__PBPromotionInfo;
typedef struct _Game__PBGameItem Game__PBGameItem;
typedef struct _Game__PBGameItemList Game__PBGameItemList;
typedef struct _Game__PBIAPProduct Game__PBIAPProduct;
typedef struct _Game__PBIAPProductPrice Game__PBIAPProductPrice;
typedef struct _Game__PBIAPProductList Game__PBIAPProductList;
typedef struct _Game__PBUserItem Game__PBUserItem;
typedef struct _Game__PBUserItemList Game__PBUserItemList;
typedef struct _Game__PBLocalizeString Game__PBLocalizeString;
typedef struct _Game__PBApp Game__PBApp;
typedef struct _Game__PBSize Game__PBSize;


/* --- enums --- */

typedef enum _Game__PBOpenInfoType {
  GAME__PBOPEN_INFO_TYPE__OPEN_TO_FRIEND = 0,
  GAME__PBOPEN_INFO_TYPE__OPEN_NO = 1,
  GAME__PBOPEN_INFO_TYPE__OPEN_ALL = 2
} Game__PBOpenInfoType;
typedef enum _Game__PBGameCurrency {
  GAME__PBGAME_CURRENCY__Coin = 0,
  GAME__PBGAME_CURRENCY__Ingot = 1
} Game__PBGameCurrency;
typedef enum _Game__PBDrawItemType {
  GAME__PBDRAW_ITEM_TYPE__DrawNomal = 0,
  GAME__PBDRAW_ITEM_TYPE__DrawTool = 1,
  GAME__PBDRAW_ITEM_TYPE__DrawTaoBao = 9999
} Game__PBDrawItemType;
typedef enum _Game__PBDiceItemType {
  GAME__PBDICE_ITEM_TYPE__DiceNomal = 0
} Game__PBDiceItemType;
typedef enum _Game__PBGameItemConsumeType {
  GAME__PBGAME_ITEM_CONSUME_TYPE__NonConsumable = 1,
  GAME__PBGAME_ITEM_CONSUME_TYPE__AmountConsumable = 2,
  GAME__PBGAME_ITEM_CONSUME_TYPE__TimeConsumable = 3
} Game__PBGameItemConsumeType;
typedef enum _Game__PBGameTimeUnit {
  GAME__PBGAME_TIME_UNIT__Hour = 1,
  GAME__PBGAME_TIME_UNIT__Day = 2,
  GAME__PBGAME_TIME_UNIT__Month = 3,
  GAME__PBGAME_TIME_UNIT__Year = 4
} Game__PBGameTimeUnit;
typedef enum _Game__PBIAPProductType {
  GAME__PBIAPPRODUCT_TYPE__IAPCoin = 1,
  GAME__PBIAPPRODUCT_TYPE__IAPIngot = 2
} Game__PBIAPProductType;

/* --- messages --- */

struct  _Game__PBKeyValue
{
  ProtobufCMessage base;
  char *name;
  char *value;
};
#define GAME__PBKEY_VALUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbkey_value__descriptor) \
    , NULL, NULL }


struct  _Game__PBSNSUser
{
  ProtobufCMessage base;
  int32_t type;
  char *userid;
  char *nickname;
  char *accesstoken;
  char *accesstokensecret;
  char *refreshtoken;
  protobuf_c_boolean has_expiretime;
  int32_t expiretime;
  char *qqopenid;
};
#define GAME__PBSNSUSER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsnsuser__descriptor) \
    , 0, NULL, NULL, NULL, NULL, NULL, 0,0, NULL }


struct  _Game__PBUserLevel
{
  ProtobufCMessage base;
  char *gameid;
  protobuf_c_boolean has_level;
  int32_t level;
  protobuf_c_boolean has_exp;
  int64_t exp;
};
#define GAME__PBUSER_LEVEL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_level__descriptor) \
    , NULL, 0,1, 0,0 }


struct  _Game__PBGameUser
{
  ProtobufCMessage base;
  char *userid;
  char *nickname;
  char *avatar;
  protobuf_c_boolean has_gender;
  protobuf_c_boolean gender;
  size_t n_snsusers;
  Game__PBSNSUser **snsusers;
  char *location;
  protobuf_c_boolean has_userlevel;
  int32_t userlevel;
  char *facetimeid;
  protobuf_c_boolean has_seatid;
  int32_t seatid;
  protobuf_c_boolean has_isplaying;
  protobuf_c_boolean isplaying;
  protobuf_c_boolean has_istakenover;
  protobuf_c_boolean istakenover;
  size_t n_attributes;
  Game__PBKeyValue **attributes;
  char *email;
  char *password;
  char *birthday;
  protobuf_c_boolean has_zodiac;
  int32_t zodiac;
  protobuf_c_boolean has_guesswordlanguage;
  int32_t guesswordlanguage;
  char *backgroundurl;
  char *devicetoken;
  char *countrycode;
  char *language;
  protobuf_c_boolean has_level;
  int32_t level;
  protobuf_c_boolean has_experience;
  int64_t experience;
  protobuf_c_boolean has_coinbalance;
  int32_t coinbalance;
  protobuf_c_boolean has_diamondbalance;
  int32_t diamondbalance;
  protobuf_c_boolean has_ingotbalance;
  int32_t ingotbalance;
  size_t n_items;
  Game__PBUserItem **items;
  char *devicemodel;
  char *deviceos;
  char *deviceid;
  char *devicetype;
  char *bloodgroup;
  protobuf_c_boolean has_fancount;
  int32_t fancount;
  protobuf_c_boolean has_followcount;
  int32_t followcount;
  protobuf_c_boolean has_longitude;
  float longitude;
  protobuf_c_boolean has_latitude;
  float latitude;
  protobuf_c_boolean has_isjailbroken;
  protobuf_c_boolean isjailbroken;
  protobuf_c_boolean has_openinfotype;
  Game__PBOpenInfoType openinfotype;
  protobuf_c_boolean has_opuscoverflowtype;
  int32_t opuscoverflowtype;
  char *signature;
};
#define GAME__PBGAME_USER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbgame_user__descriptor) \
    , NULL, NULL, NULL, 0,0, 0,NULL, NULL, 0,0, NULL, 0,0, 0,1, 0,0, 0,NULL, NULL, NULL, NULL, 0,0, 0,1, NULL, NULL, NULL, NULL, 0,0, 0,0, 0,0, 0,0, 0,0, 0,NULL, NULL, NULL, NULL, NULL, NULL, 0,0, 0,0, 0,0, 0,0, 0,0, 0,GAME__PBOPEN_INFO_TYPE__OPEN_TO_FRIEND, 0,0, NULL }


struct  _Game__PBGameSession
{
  ProtobufCMessage base;
  char *gameid;
  int64_t sessionid;
  char *name;
  char *createby;
  protobuf_c_boolean has_createtime;
  int32_t createtime;
  char *host;
  protobuf_c_boolean has_status;
  int32_t status;
  char *currentplayuserid;
  char *nextplayuserid;
  char *password;
  protobuf_c_boolean has_ruletype;
  int32_t ruletype;
  size_t n_users;
  Game__PBGameUser **users;
};
#define GAME__PBGAME_SESSION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbgame_session__descriptor) \
    , NULL, 0, NULL, NULL, 0,0, NULL, 0,0, NULL, NULL, NULL, 0,0, 0,NULL }


struct  _Game__PBGameSessionChanged
{
  ProtobufCMessage base;
  protobuf_c_boolean has_sessionid;
  int64_t sessionid;
  protobuf_c_boolean has_status;
  int32_t status;
  char *currentplayuserid;
  size_t n_usersadded;
  Game__PBGameUser **usersadded;
  size_t n_useridsdeleted;
  char **useridsdeleted;
  size_t n_usersupdated;
  Game__PBGameUser **usersupdated;
};
#define GAME__PBGAME_SESSION_CHANGED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbgame_session_changed__descriptor) \
    , 0,0, 0,0, NULL, 0,NULL, 0,NULL, 0,NULL }


struct  _Game__PBDrawBg
{
  ProtobufCMessage base;
  char *bgid;
  char *localurl;
  char *remoteurl;
  protobuf_c_boolean has_showstyle;
  int32_t showstyle;
};
#define GAME__PBDRAW_BG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbdraw_bg__descriptor) \
    , NULL, NULL, NULL, 0,0 }


struct  _Game__PBSettingInfo
{
  ProtobufCMessage base;
  int32_t tag;
  protobuf_c_boolean has_cliptype;
  int32_t cliptype;
};
#define GAME__PBSETTING_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsetting_info__descriptor) \
    , 0, 0,0 }


struct  _Game__PBDrawAction
{
  ProtobufCMessage base;
  int32_t type;
  size_t n_points;
  int32_t *points;
  protobuf_c_boolean has_width;
  float width;
  protobuf_c_boolean has_color;
  int32_t color;
  protobuf_c_boolean has_pentype;
  int32_t pentype;
  protobuf_c_boolean has_shapetype;
  int32_t shapetype;
  size_t n_rectcomponent;
  float *rectcomponent;
  size_t n_pointsx;
  float *pointsx;
  size_t n_pointsy;
  float *pointsy;
  protobuf_c_boolean has_bettercolor;
  int32_t bettercolor;
  Game__PBDrawBg *drawbg;
  protobuf_c_boolean has_shadowoffsetx;
  float shadowoffsetx;
  protobuf_c_boolean has_shadowoffsety;
  float shadowoffsety;
  protobuf_c_boolean has_shadowcolor;
  int32_t shadowcolor;
  protobuf_c_boolean has_shadowblur;
  float shadowblur;
  Game__PBSettingInfo *settinginfo;
};
#define GAME__PBDRAW_ACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbdraw_action__descriptor) \
    , 0, 0,NULL, 0,0, 0,0, 0,0, 0,0, 0,NULL, 0,NULL, 0,NULL, 0,0, NULL, 0,0, 0,0, 0,0, 0,0, NULL }


struct  _Game__PBMessage
{
  ProtobufCMessage base;
  char *messageid;
  char *from;
  char *to;
  protobuf_c_boolean has_status;
  int32_t status;
  protobuf_c_boolean has_type;
  int32_t type;
  char *text;
  size_t n_drawdata;
  Game__PBDrawAction **drawdata;
  protobuf_c_boolean has_createdate;
  int32_t createdate;
  protobuf_c_boolean has_drawdataversion;
  int32_t drawdataversion;
  Game__PBSize *canvassize;
  protobuf_c_boolean has_longitude;
  double longitude;
  protobuf_c_boolean has_latitude;
  double latitude;
  char *reqmessageid;
  protobuf_c_boolean has_replyresult;
  int32_t replyresult;
  char *imageurl;
  char *thumbimageurl;
};
#define GAME__PBMESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbmessage__descriptor) \
    , NULL, NULL, NULL, 0,0, 0,0, NULL, 0,NULL, 0,0, 0,0, NULL, 0,0, 0,0, NULL, 0,0, NULL, NULL }


struct  _Game__PBMessageStat
{
  ProtobufCMessage base;
  char *userid;
  char *frienduserid;
  char *friendnickname;
  char *friendavatar;
  protobuf_c_boolean has_friendgender;
  protobuf_c_boolean friendgender;
  char *messageid;
  char *from;
  char *to;
  char *text;
  size_t n_drawdata;
  Game__PBDrawAction **drawdata;
  protobuf_c_boolean has_createdate;
  int32_t createdate;
  protobuf_c_boolean has_type;
  int32_t type;
  protobuf_c_boolean has_modifieddate;
  int32_t modifieddate;
  protobuf_c_boolean has_totalmessagecount;
  int32_t totalmessagecount;
  protobuf_c_boolean has_newmessagecount;
  int32_t newmessagecount;
};
#define GAME__PBMESSAGE_STAT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbmessage_stat__descriptor) \
    , NULL, NULL, NULL, NULL, 0,0, NULL, NULL, NULL, NULL, 0,NULL, 0,0, 0,0, 0,0, 0,0, 0,0 }


struct  _Game__PBUserBasicInfo
{
  ProtobufCMessage base;
  char *userid;
  char *nickname;
  char *avatar;
  char *gender;
};
#define GAME__PBUSER_BASIC_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_basic_info__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Game__PBUserResult
{
  ProtobufCMessage base;
  char *userid;
  protobuf_c_boolean win;
  int32_t gaincoins;
};
#define GAME__PBUSER_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_result__descriptor) \
    , NULL, 0, 0 }


struct  _Game__PBItemPriceInfo
{
  ProtobufCMessage base;
  int32_t price;
  protobuf_c_boolean has_currency;
  Game__PBGameCurrency currency;
};
#define GAME__PBITEM_PRICE_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbitem_price_info__descriptor) \
    , 0, 0,0 }


struct  _Game__PBPromotionInfo
{
  ProtobufCMessage base;
  int32_t price;
  protobuf_c_boolean has_startdate;
  int32_t startdate;
  protobuf_c_boolean has_expiredate;
  int32_t expiredate;
};
#define GAME__PBPROMOTION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbpromotion_info__descriptor) \
    , 0, 0,0, 0,0 }


struct  _Game__PBGameItem
{
  ProtobufCMessage base;
  int32_t itemid;
  char *name;
  char *desc;
  char *url;
  protobuf_c_boolean has_consumetype;
  Game__PBGameItemConsumeType consumetype;
  char *image;
  char *demoimage;
  protobuf_c_boolean has_type;
  int32_t type;
  char *appleproductid;
  Game__PBItemPriceInfo *priceinfo;
  Game__PBPromotionInfo *promotioninfo;
  protobuf_c_boolean has_defaultsalecount;
  int32_t defaultsalecount;
  protobuf_c_boolean has_usagelifeunit;
  Game__PBGameTimeUnit usagelifeunit;
  protobuf_c_boolean has_usagelife;
  int32_t usagelife;
};
#define GAME__PBGAME_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbgame_item__descriptor) \
    , 0, NULL, NULL, NULL, 0,0, NULL, NULL, 0,0, NULL, NULL, NULL, 0,0, 0,0, 0,0 }


struct  _Game__PBGameItemList
{
  ProtobufCMessage base;
  size_t n_items;
  Game__PBGameItem **items;
};
#define GAME__PBGAME_ITEM_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbgame_item_list__descriptor) \
    , 0,NULL }


struct  _Game__PBIAPProduct
{
  ProtobufCMessage base;
  Game__PBIAPProductType type;
  char *appleproductid;
  char *alipayproductid;
  char *name;
  char *desc;
  protobuf_c_boolean has_count;
  int32_t count;
  char *totalprice;
  char *currency;
  char *country;
  char *saving;
  char *taobaourl;
  size_t n_prices;
  Game__PBIAPProductPrice **prices;
};
#define GAME__PBIAPPRODUCT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbiapproduct__descriptor) \
    , 0, NULL, NULL, NULL, NULL, 0,1, NULL, NULL, NULL, NULL, NULL, 0,NULL }


struct  _Game__PBIAPProductPrice
{
  ProtobufCMessage base;
  char *price;
  char *currency;
  char *country;
  char *saving;
};
#define GAME__PBIAPPRODUCT_PRICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbiapproduct_price__descriptor) \
    , NULL, NULL, NULL, NULL }


struct  _Game__PBIAPProductList
{
  ProtobufCMessage base;
  size_t n_products;
  Game__PBIAPProduct **products;
};
#define GAME__PBIAPPRODUCT_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbiapproduct_list__descriptor) \
    , 0,NULL }


struct  _Game__PBUserItem
{
  ProtobufCMessage base;
  int32_t itemid;
  protobuf_c_boolean has_count;
  int32_t count;
  protobuf_c_boolean has_createdate;
  int32_t createdate;
  protobuf_c_boolean has_modifydate;
  int32_t modifydate;
  protobuf_c_boolean has_expiredate;
  int32_t expiredate;
};
#define GAME__PBUSER_ITEM__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_item__descriptor) \
    , 0, 0,0, 0,0, 0,0, 0,0 }


struct  _Game__PBUserItemList
{
  ProtobufCMessage base;
  size_t n_useritems;
  Game__PBUserItem **useritems;
};
#define GAME__PBUSER_ITEM_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_item_list__descriptor) \
    , 0,NULL }


struct  _Game__PBLocalizeString
{
  ProtobufCMessage base;
  char *languagecode;
  char *text;
  char *localizedtext;
};
#define GAME__PBLOCALIZE_STRING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pblocalize_string__descriptor) \
    , NULL, NULL, NULL }


struct  _Game__PBApp
{
  ProtobufCMessage base;
  size_t n_name;
  Game__PBLocalizeString **name;
  char *appid;
  size_t n_desc;
  Game__PBLocalizeString **desc;
  char *downloadurl;
  char *logo;
};
#define GAME__PBAPP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbapp__descriptor) \
    , 0,NULL, NULL, 0,NULL, NULL, NULL }


struct  _Game__PBSize
{
  ProtobufCMessage base;
  protobuf_c_boolean has_width;
  float width;
  protobuf_c_boolean has_height;
  float height;
};
#define GAME__PBSIZE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsize__descriptor) \
    , 0,304, 0,320 }


/* Game__PBKeyValue methods */
void   game__pbkey_value__init
                     (Game__PBKeyValue         *message);
size_t game__pbkey_value__get_packed_size
                     (const Game__PBKeyValue   *message);
size_t game__pbkey_value__pack
                     (const Game__PBKeyValue   *message,
                      uint8_t             *out);
size_t game__pbkey_value__pack_to_buffer
                     (const Game__PBKeyValue   *message,
                      ProtobufCBuffer     *buffer);
Game__PBKeyValue *
       game__pbkey_value__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbkey_value__free_unpacked
                     (Game__PBKeyValue *message,
                      ProtobufCAllocator *allocator);
/* Game__PBSNSUser methods */
void   game__pbsnsuser__init
                     (Game__PBSNSUser         *message);
size_t game__pbsnsuser__get_packed_size
                     (const Game__PBSNSUser   *message);
size_t game__pbsnsuser__pack
                     (const Game__PBSNSUser   *message,
                      uint8_t             *out);
size_t game__pbsnsuser__pack_to_buffer
                     (const Game__PBSNSUser   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSNSUser *
       game__pbsnsuser__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsnsuser__free_unpacked
                     (Game__PBSNSUser *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserLevel methods */
void   game__pbuser_level__init
                     (Game__PBUserLevel         *message);
size_t game__pbuser_level__get_packed_size
                     (const Game__PBUserLevel   *message);
size_t game__pbuser_level__pack
                     (const Game__PBUserLevel   *message,
                      uint8_t             *out);
size_t game__pbuser_level__pack_to_buffer
                     (const Game__PBUserLevel   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserLevel *
       game__pbuser_level__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_level__free_unpacked
                     (Game__PBUserLevel *message,
                      ProtobufCAllocator *allocator);
/* Game__PBGameUser methods */
void   game__pbgame_user__init
                     (Game__PBGameUser         *message);
size_t game__pbgame_user__get_packed_size
                     (const Game__PBGameUser   *message);
size_t game__pbgame_user__pack
                     (const Game__PBGameUser   *message,
                      uint8_t             *out);
size_t game__pbgame_user__pack_to_buffer
                     (const Game__PBGameUser   *message,
                      ProtobufCBuffer     *buffer);
Game__PBGameUser *
       game__pbgame_user__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbgame_user__free_unpacked
                     (Game__PBGameUser *message,
                      ProtobufCAllocator *allocator);
/* Game__PBGameSession methods */
void   game__pbgame_session__init
                     (Game__PBGameSession         *message);
size_t game__pbgame_session__get_packed_size
                     (const Game__PBGameSession   *message);
size_t game__pbgame_session__pack
                     (const Game__PBGameSession   *message,
                      uint8_t             *out);
size_t game__pbgame_session__pack_to_buffer
                     (const Game__PBGameSession   *message,
                      ProtobufCBuffer     *buffer);
Game__PBGameSession *
       game__pbgame_session__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbgame_session__free_unpacked
                     (Game__PBGameSession *message,
                      ProtobufCAllocator *allocator);
/* Game__PBGameSessionChanged methods */
void   game__pbgame_session_changed__init
                     (Game__PBGameSessionChanged         *message);
size_t game__pbgame_session_changed__get_packed_size
                     (const Game__PBGameSessionChanged   *message);
size_t game__pbgame_session_changed__pack
                     (const Game__PBGameSessionChanged   *message,
                      uint8_t             *out);
size_t game__pbgame_session_changed__pack_to_buffer
                     (const Game__PBGameSessionChanged   *message,
                      ProtobufCBuffer     *buffer);
Game__PBGameSessionChanged *
       game__pbgame_session_changed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbgame_session_changed__free_unpacked
                     (Game__PBGameSessionChanged *message,
                      ProtobufCAllocator *allocator);
/* Game__PBDrawBg methods */
void   game__pbdraw_bg__init
                     (Game__PBDrawBg         *message);
size_t game__pbdraw_bg__get_packed_size
                     (const Game__PBDrawBg   *message);
size_t game__pbdraw_bg__pack
                     (const Game__PBDrawBg   *message,
                      uint8_t             *out);
size_t game__pbdraw_bg__pack_to_buffer
                     (const Game__PBDrawBg   *message,
                      ProtobufCBuffer     *buffer);
Game__PBDrawBg *
       game__pbdraw_bg__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbdraw_bg__free_unpacked
                     (Game__PBDrawBg *message,
                      ProtobufCAllocator *allocator);
/* Game__PBSettingInfo methods */
void   game__pbsetting_info__init
                     (Game__PBSettingInfo         *message);
size_t game__pbsetting_info__get_packed_size
                     (const Game__PBSettingInfo   *message);
size_t game__pbsetting_info__pack
                     (const Game__PBSettingInfo   *message,
                      uint8_t             *out);
size_t game__pbsetting_info__pack_to_buffer
                     (const Game__PBSettingInfo   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSettingInfo *
       game__pbsetting_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsetting_info__free_unpacked
                     (Game__PBSettingInfo *message,
                      ProtobufCAllocator *allocator);
/* Game__PBDrawAction methods */
void   game__pbdraw_action__init
                     (Game__PBDrawAction         *message);
size_t game__pbdraw_action__get_packed_size
                     (const Game__PBDrawAction   *message);
size_t game__pbdraw_action__pack
                     (const Game__PBDrawAction   *message,
                      uint8_t             *out);
size_t game__pbdraw_action__pack_to_buffer
                     (const Game__PBDrawAction   *message,
                      ProtobufCBuffer     *buffer);
Game__PBDrawAction *
       game__pbdraw_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbdraw_action__free_unpacked
                     (Game__PBDrawAction *message,
                      ProtobufCAllocator *allocator);
/* Game__PBMessage methods */
void   game__pbmessage__init
                     (Game__PBMessage         *message);
size_t game__pbmessage__get_packed_size
                     (const Game__PBMessage   *message);
size_t game__pbmessage__pack
                     (const Game__PBMessage   *message,
                      uint8_t             *out);
size_t game__pbmessage__pack_to_buffer
                     (const Game__PBMessage   *message,
                      ProtobufCBuffer     *buffer);
Game__PBMessage *
       game__pbmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbmessage__free_unpacked
                     (Game__PBMessage *message,
                      ProtobufCAllocator *allocator);
/* Game__PBMessageStat methods */
void   game__pbmessage_stat__init
                     (Game__PBMessageStat         *message);
size_t game__pbmessage_stat__get_packed_size
                     (const Game__PBMessageStat   *message);
size_t game__pbmessage_stat__pack
                     (const Game__PBMessageStat   *message,
                      uint8_t             *out);
size_t game__pbmessage_stat__pack_to_buffer
                     (const Game__PBMessageStat   *message,
                      ProtobufCBuffer     *buffer);
Game__PBMessageStat *
       game__pbmessage_stat__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbmessage_stat__free_unpacked
                     (Game__PBMessageStat *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserBasicInfo methods */
void   game__pbuser_basic_info__init
                     (Game__PBUserBasicInfo         *message);
size_t game__pbuser_basic_info__get_packed_size
                     (const Game__PBUserBasicInfo   *message);
size_t game__pbuser_basic_info__pack
                     (const Game__PBUserBasicInfo   *message,
                      uint8_t             *out);
size_t game__pbuser_basic_info__pack_to_buffer
                     (const Game__PBUserBasicInfo   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserBasicInfo *
       game__pbuser_basic_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_basic_info__free_unpacked
                     (Game__PBUserBasicInfo *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserResult methods */
void   game__pbuser_result__init
                     (Game__PBUserResult         *message);
size_t game__pbuser_result__get_packed_size
                     (const Game__PBUserResult   *message);
size_t game__pbuser_result__pack
                     (const Game__PBUserResult   *message,
                      uint8_t             *out);
size_t game__pbuser_result__pack_to_buffer
                     (const Game__PBUserResult   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserResult *
       game__pbuser_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_result__free_unpacked
                     (Game__PBUserResult *message,
                      ProtobufCAllocator *allocator);
/* Game__PBItemPriceInfo methods */
void   game__pbitem_price_info__init
                     (Game__PBItemPriceInfo         *message);
size_t game__pbitem_price_info__get_packed_size
                     (const Game__PBItemPriceInfo   *message);
size_t game__pbitem_price_info__pack
                     (const Game__PBItemPriceInfo   *message,
                      uint8_t             *out);
size_t game__pbitem_price_info__pack_to_buffer
                     (const Game__PBItemPriceInfo   *message,
                      ProtobufCBuffer     *buffer);
Game__PBItemPriceInfo *
       game__pbitem_price_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbitem_price_info__free_unpacked
                     (Game__PBItemPriceInfo *message,
                      ProtobufCAllocator *allocator);
/* Game__PBPromotionInfo methods */
void   game__pbpromotion_info__init
                     (Game__PBPromotionInfo         *message);
size_t game__pbpromotion_info__get_packed_size
                     (const Game__PBPromotionInfo   *message);
size_t game__pbpromotion_info__pack
                     (const Game__PBPromotionInfo   *message,
                      uint8_t             *out);
size_t game__pbpromotion_info__pack_to_buffer
                     (const Game__PBPromotionInfo   *message,
                      ProtobufCBuffer     *buffer);
Game__PBPromotionInfo *
       game__pbpromotion_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbpromotion_info__free_unpacked
                     (Game__PBPromotionInfo *message,
                      ProtobufCAllocator *allocator);
/* Game__PBGameItem methods */
void   game__pbgame_item__init
                     (Game__PBGameItem         *message);
size_t game__pbgame_item__get_packed_size
                     (const Game__PBGameItem   *message);
size_t game__pbgame_item__pack
                     (const Game__PBGameItem   *message,
                      uint8_t             *out);
size_t game__pbgame_item__pack_to_buffer
                     (const Game__PBGameItem   *message,
                      ProtobufCBuffer     *buffer);
Game__PBGameItem *
       game__pbgame_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbgame_item__free_unpacked
                     (Game__PBGameItem *message,
                      ProtobufCAllocator *allocator);
/* Game__PBGameItemList methods */
void   game__pbgame_item_list__init
                     (Game__PBGameItemList         *message);
size_t game__pbgame_item_list__get_packed_size
                     (const Game__PBGameItemList   *message);
size_t game__pbgame_item_list__pack
                     (const Game__PBGameItemList   *message,
                      uint8_t             *out);
size_t game__pbgame_item_list__pack_to_buffer
                     (const Game__PBGameItemList   *message,
                      ProtobufCBuffer     *buffer);
Game__PBGameItemList *
       game__pbgame_item_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbgame_item_list__free_unpacked
                     (Game__PBGameItemList *message,
                      ProtobufCAllocator *allocator);
/* Game__PBIAPProduct methods */
void   game__pbiapproduct__init
                     (Game__PBIAPProduct         *message);
size_t game__pbiapproduct__get_packed_size
                     (const Game__PBIAPProduct   *message);
size_t game__pbiapproduct__pack
                     (const Game__PBIAPProduct   *message,
                      uint8_t             *out);
size_t game__pbiapproduct__pack_to_buffer
                     (const Game__PBIAPProduct   *message,
                      ProtobufCBuffer     *buffer);
Game__PBIAPProduct *
       game__pbiapproduct__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbiapproduct__free_unpacked
                     (Game__PBIAPProduct *message,
                      ProtobufCAllocator *allocator);
/* Game__PBIAPProductPrice methods */
void   game__pbiapproduct_price__init
                     (Game__PBIAPProductPrice         *message);
size_t game__pbiapproduct_price__get_packed_size
                     (const Game__PBIAPProductPrice   *message);
size_t game__pbiapproduct_price__pack
                     (const Game__PBIAPProductPrice   *message,
                      uint8_t             *out);
size_t game__pbiapproduct_price__pack_to_buffer
                     (const Game__PBIAPProductPrice   *message,
                      ProtobufCBuffer     *buffer);
Game__PBIAPProductPrice *
       game__pbiapproduct_price__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbiapproduct_price__free_unpacked
                     (Game__PBIAPProductPrice *message,
                      ProtobufCAllocator *allocator);
/* Game__PBIAPProductList methods */
void   game__pbiapproduct_list__init
                     (Game__PBIAPProductList         *message);
size_t game__pbiapproduct_list__get_packed_size
                     (const Game__PBIAPProductList   *message);
size_t game__pbiapproduct_list__pack
                     (const Game__PBIAPProductList   *message,
                      uint8_t             *out);
size_t game__pbiapproduct_list__pack_to_buffer
                     (const Game__PBIAPProductList   *message,
                      ProtobufCBuffer     *buffer);
Game__PBIAPProductList *
       game__pbiapproduct_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbiapproduct_list__free_unpacked
                     (Game__PBIAPProductList *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserItem methods */
void   game__pbuser_item__init
                     (Game__PBUserItem         *message);
size_t game__pbuser_item__get_packed_size
                     (const Game__PBUserItem   *message);
size_t game__pbuser_item__pack
                     (const Game__PBUserItem   *message,
                      uint8_t             *out);
size_t game__pbuser_item__pack_to_buffer
                     (const Game__PBUserItem   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserItem *
       game__pbuser_item__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_item__free_unpacked
                     (Game__PBUserItem *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserItemList methods */
void   game__pbuser_item_list__init
                     (Game__PBUserItemList         *message);
size_t game__pbuser_item_list__get_packed_size
                     (const Game__PBUserItemList   *message);
size_t game__pbuser_item_list__pack
                     (const Game__PBUserItemList   *message,
                      uint8_t             *out);
size_t game__pbuser_item_list__pack_to_buffer
                     (const Game__PBUserItemList   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserItemList *
       game__pbuser_item_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_item_list__free_unpacked
                     (Game__PBUserItemList *message,
                      ProtobufCAllocator *allocator);
/* Game__PBLocalizeString methods */
void   game__pblocalize_string__init
                     (Game__PBLocalizeString         *message);
size_t game__pblocalize_string__get_packed_size
                     (const Game__PBLocalizeString   *message);
size_t game__pblocalize_string__pack
                     (const Game__PBLocalizeString   *message,
                      uint8_t             *out);
size_t game__pblocalize_string__pack_to_buffer
                     (const Game__PBLocalizeString   *message,
                      ProtobufCBuffer     *buffer);
Game__PBLocalizeString *
       game__pblocalize_string__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pblocalize_string__free_unpacked
                     (Game__PBLocalizeString *message,
                      ProtobufCAllocator *allocator);
/* Game__PBApp methods */
void   game__pbapp__init
                     (Game__PBApp         *message);
size_t game__pbapp__get_packed_size
                     (const Game__PBApp   *message);
size_t game__pbapp__pack
                     (const Game__PBApp   *message,
                      uint8_t             *out);
size_t game__pbapp__pack_to_buffer
                     (const Game__PBApp   *message,
                      ProtobufCBuffer     *buffer);
Game__PBApp *
       game__pbapp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbapp__free_unpacked
                     (Game__PBApp *message,
                      ProtobufCAllocator *allocator);
/* Game__PBSize methods */
void   game__pbsize__init
                     (Game__PBSize         *message);
size_t game__pbsize__get_packed_size
                     (const Game__PBSize   *message);
size_t game__pbsize__pack
                     (const Game__PBSize   *message,
                      uint8_t             *out);
size_t game__pbsize__pack_to_buffer
                     (const Game__PBSize   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSize *
       game__pbsize__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsize__free_unpacked
                     (Game__PBSize *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__PBKeyValue_Closure)
                 (const Game__PBKeyValue *message,
                  void *closure_data);
typedef void (*Game__PBSNSUser_Closure)
                 (const Game__PBSNSUser *message,
                  void *closure_data);
typedef void (*Game__PBUserLevel_Closure)
                 (const Game__PBUserLevel *message,
                  void *closure_data);
typedef void (*Game__PBGameUser_Closure)
                 (const Game__PBGameUser *message,
                  void *closure_data);
typedef void (*Game__PBGameSession_Closure)
                 (const Game__PBGameSession *message,
                  void *closure_data);
typedef void (*Game__PBGameSessionChanged_Closure)
                 (const Game__PBGameSessionChanged *message,
                  void *closure_data);
typedef void (*Game__PBDrawBg_Closure)
                 (const Game__PBDrawBg *message,
                  void *closure_data);
typedef void (*Game__PBSettingInfo_Closure)
                 (const Game__PBSettingInfo *message,
                  void *closure_data);
typedef void (*Game__PBDrawAction_Closure)
                 (const Game__PBDrawAction *message,
                  void *closure_data);
typedef void (*Game__PBMessage_Closure)
                 (const Game__PBMessage *message,
                  void *closure_data);
typedef void (*Game__PBMessageStat_Closure)
                 (const Game__PBMessageStat *message,
                  void *closure_data);
typedef void (*Game__PBUserBasicInfo_Closure)
                 (const Game__PBUserBasicInfo *message,
                  void *closure_data);
typedef void (*Game__PBUserResult_Closure)
                 (const Game__PBUserResult *message,
                  void *closure_data);
typedef void (*Game__PBItemPriceInfo_Closure)
                 (const Game__PBItemPriceInfo *message,
                  void *closure_data);
typedef void (*Game__PBPromotionInfo_Closure)
                 (const Game__PBPromotionInfo *message,
                  void *closure_data);
typedef void (*Game__PBGameItem_Closure)
                 (const Game__PBGameItem *message,
                  void *closure_data);
typedef void (*Game__PBGameItemList_Closure)
                 (const Game__PBGameItemList *message,
                  void *closure_data);
typedef void (*Game__PBIAPProduct_Closure)
                 (const Game__PBIAPProduct *message,
                  void *closure_data);
typedef void (*Game__PBIAPProductPrice_Closure)
                 (const Game__PBIAPProductPrice *message,
                  void *closure_data);
typedef void (*Game__PBIAPProductList_Closure)
                 (const Game__PBIAPProductList *message,
                  void *closure_data);
typedef void (*Game__PBUserItem_Closure)
                 (const Game__PBUserItem *message,
                  void *closure_data);
typedef void (*Game__PBUserItemList_Closure)
                 (const Game__PBUserItemList *message,
                  void *closure_data);
typedef void (*Game__PBLocalizeString_Closure)
                 (const Game__PBLocalizeString *message,
                  void *closure_data);
typedef void (*Game__PBApp_Closure)
                 (const Game__PBApp *message,
                  void *closure_data);
typedef void (*Game__PBSize_Closure)
                 (const Game__PBSize *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    game__pbopen_info_type__descriptor;
extern const ProtobufCEnumDescriptor    game__pbgame_currency__descriptor;
extern const ProtobufCEnumDescriptor    game__pbdraw_item_type__descriptor;
extern const ProtobufCEnumDescriptor    game__pbdice_item_type__descriptor;
extern const ProtobufCEnumDescriptor    game__pbgame_item_consume_type__descriptor;
extern const ProtobufCEnumDescriptor    game__pbgame_time_unit__descriptor;
extern const ProtobufCEnumDescriptor    game__pbiapproduct_type__descriptor;
extern const ProtobufCMessageDescriptor game__pbkey_value__descriptor;
extern const ProtobufCMessageDescriptor game__pbsnsuser__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_level__descriptor;
extern const ProtobufCMessageDescriptor game__pbgame_user__descriptor;
extern const ProtobufCMessageDescriptor game__pbgame_session__descriptor;
extern const ProtobufCMessageDescriptor game__pbgame_session_changed__descriptor;
extern const ProtobufCMessageDescriptor game__pbdraw_bg__descriptor;
extern const ProtobufCMessageDescriptor game__pbsetting_info__descriptor;
extern const ProtobufCMessageDescriptor game__pbdraw_action__descriptor;
extern const ProtobufCMessageDescriptor game__pbmessage__descriptor;
extern const ProtobufCMessageDescriptor game__pbmessage_stat__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_basic_info__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_result__descriptor;
extern const ProtobufCMessageDescriptor game__pbitem_price_info__descriptor;
extern const ProtobufCMessageDescriptor game__pbpromotion_info__descriptor;
extern const ProtobufCMessageDescriptor game__pbgame_item__descriptor;
extern const ProtobufCMessageDescriptor game__pbgame_item_list__descriptor;
extern const ProtobufCMessageDescriptor game__pbiapproduct__descriptor;
extern const ProtobufCMessageDescriptor game__pbiapproduct_price__descriptor;
extern const ProtobufCMessageDescriptor game__pbiapproduct_list__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_item__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_item_list__descriptor;
extern const ProtobufCMessageDescriptor game__pblocalize_string__descriptor;
extern const ProtobufCMessageDescriptor game__pbapp__descriptor;
extern const ProtobufCMessageDescriptor game__pbsize__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_GameBasic_2eproto__INCLUDED */
