/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "Opus.pb-c.h"
void   game__pbopus__init
                     (Game__PBOpus         *message)
{
  static Game__PBOpus init_value = GAME__PBOPUS__INIT;
  *message = init_value;
}
size_t game__pbopus__get_packed_size
                     (const Game__PBOpus *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbopus__pack
                     (const Game__PBOpus *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbopus__pack_to_buffer
                     (const Game__PBOpus *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBOpus *
       game__pbopus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBOpus *)
     protobuf_c_message_unpack (&game__pbopus__descriptor,
                                allocator, len, data);
}
void   game__pbopus__free_unpacked
                     (Game__PBOpus *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbopus_action__init
                     (Game__PBOpusAction         *message)
{
  static Game__PBOpusAction init_value = GAME__PBOPUS_ACTION__INIT;
  *message = init_value;
}
size_t game__pbopus_action__get_packed_size
                     (const Game__PBOpusAction *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus_action__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbopus_action__pack
                     (const Game__PBOpusAction *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus_action__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbopus_action__pack_to_buffer
                     (const Game__PBOpusAction *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus_action__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBOpusAction *
       game__pbopus_action__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBOpusAction *)
     protobuf_c_message_unpack (&game__pbopus_action__descriptor,
                                allocator, len, data);
}
void   game__pbopus_action__free_unpacked
                     (Game__PBOpusAction *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbopus_action__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbaction_comment__init
                     (Game__PBActionComment         *message)
{
  static Game__PBActionComment init_value = GAME__PBACTION_COMMENT__INIT;
  *message = init_value;
}
size_t game__pbaction_comment__get_packed_size
                     (const Game__PBActionComment *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_comment__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbaction_comment__pack
                     (const Game__PBActionComment *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_comment__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbaction_comment__pack_to_buffer
                     (const Game__PBActionComment *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_comment__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBActionComment *
       game__pbaction_comment__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBActionComment *)
     protobuf_c_message_unpack (&game__pbaction_comment__descriptor,
                                allocator, len, data);
}
void   game__pbaction_comment__free_unpacked
                     (Game__PBActionComment *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_comment__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbaction_flower__init
                     (Game__PBActionFlower         *message)
{
  static Game__PBActionFlower init_value = GAME__PBACTION_FLOWER__INIT;
  *message = init_value;
}
size_t game__pbaction_flower__get_packed_size
                     (const Game__PBActionFlower *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_flower__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbaction_flower__pack
                     (const Game__PBActionFlower *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_flower__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbaction_flower__pack_to_buffer
                     (const Game__PBActionFlower *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_flower__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBActionFlower *
       game__pbaction_flower__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBActionFlower *)
     protobuf_c_message_unpack (&game__pbaction_flower__descriptor,
                                allocator, len, data);
}
void   game__pbaction_flower__free_unpacked
                     (Game__PBActionFlower *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_flower__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbaction_guess__init
                     (Game__PBActionGuess         *message)
{
  static Game__PBActionGuess init_value = GAME__PBACTION_GUESS__INIT;
  *message = init_value;
}
size_t game__pbaction_guess__get_packed_size
                     (const Game__PBActionGuess *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_guess__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbaction_guess__pack
                     (const Game__PBActionGuess *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_guess__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbaction_guess__pack_to_buffer
                     (const Game__PBActionGuess *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_guess__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBActionGuess *
       game__pbaction_guess__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBActionGuess *)
     protobuf_c_message_unpack (&game__pbaction_guess__descriptor,
                                allocator, len, data);
}
void   game__pbaction_guess__free_unpacked
                     (Game__PBActionGuess *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_guess__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbaction_times__init
                     (Game__PBActionTimes         *message)
{
  static Game__PBActionTimes init_value = GAME__PBACTION_TIMES__INIT;
  *message = init_value;
}
size_t game__pbaction_times__get_packed_size
                     (const Game__PBActionTimes *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_times__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbaction_times__pack
                     (const Game__PBActionTimes *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_times__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbaction_times__pack_to_buffer
                     (const Game__PBActionTimes *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_times__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBActionTimes *
       game__pbaction_times__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBActionTimes *)
     protobuf_c_message_unpack (&game__pbaction_times__descriptor,
                                allocator, len, data);
}
void   game__pbaction_times__free_unpacked
                     (Game__PBActionTimes *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbaction_times__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbtimeline__init
                     (Game__PBTimeline         *message)
{
  static Game__PBTimeline init_value = GAME__PBTIMELINE__INIT;
  *message = init_value;
}
size_t game__pbtimeline__get_packed_size
                     (const Game__PBTimeline *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbtimeline__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbtimeline__pack
                     (const Game__PBTimeline *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbtimeline__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbtimeline__pack_to_buffer
                     (const Game__PBTimeline *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbtimeline__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBTimeline *
       game__pbtimeline__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBTimeline *)
     protobuf_c_message_unpack (&game__pbtimeline__descriptor,
                                allocator, len, data);
}
void   game__pbtimeline__free_unpacked
                     (Game__PBTimeline *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbtimeline__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor game__pbopus__field_descriptors[17] =
{
  {
    "opusId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, opusid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "aim",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    PROTOBUF_C_OFFSETOF(Game__PBOpus, has_aim),
    PROTOBUF_C_OFFSETOF(Game__PBOpus, aim),
    &game__pbopus_aim__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "desc",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, desc),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "image",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, image),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "thumbImage",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, thumbimage),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dataUrl",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, dataurl),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBOpus, has_createdate),
    PROTOBUF_C_OFFSETOF(Game__PBOpus, createdate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    20,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBOpus, has_status),
    PROTOBUF_C_OFFSETOF(Game__PBOpus, status),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceType",
    25,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBOpus, has_devicetype),
    PROTOBUF_C_OFFSETOF(Game__PBOpus, devicetype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "deviceName",
    26,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, devicename),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "appId",
    28,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, appid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "author",
    35,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, author),
    &game__pbgame_user__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "targetUser",
    41,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, targetuser),
    &game__pbgame_user__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "contestId",
    42,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, contestid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionTimes",
    45,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBOpus, n_actiontimes),
    PROTOBUF_C_OFFSETOF(Game__PBOpus, actiontimes),
    &game__pbaction_times__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "singOpus",
    102,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpus, singopus),
    &game__pbsing_opus__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbopus__field_indices_by_name[] = {
  15,   /* field[15] = actionTimes */
  1,   /* field[1] = aim */
  11,   /* field[11] = appId */
  12,   /* field[12] = author */
  14,   /* field[14] = contestId */
  7,   /* field[7] = createDate */
  6,   /* field[6] = dataUrl */
  3,   /* field[3] = desc */
  10,   /* field[10] = deviceName */
  9,   /* field[9] = deviceType */
  4,   /* field[4] = image */
  2,   /* field[2] = name */
  0,   /* field[0] = opusId */
  16,   /* field[16] = singOpus */
  8,   /* field[8] = status */
  13,   /* field[13] = targetUser */
  5,   /* field[5] = thumbImage */
};
static const ProtobufCIntRange game__pbopus__number_ranges[10 + 1] =
{
  { 1, 0 },
  { 9, 6 },
  { 15, 7 },
  { 20, 8 },
  { 25, 9 },
  { 28, 11 },
  { 35, 12 },
  { 41, 13 },
  { 45, 15 },
  { 102, 16 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor game__pbopus__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBOpus",
  "PBOpus",
  "Game__PBOpus",
  "game",
  sizeof(Game__PBOpus),
  17,
  game__pbopus__field_descriptors,
  game__pbopus__field_indices_by_name,
  10,  game__pbopus__number_ranges,
  (ProtobufCMessageInit) game__pbopus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbopus_action__field_descriptors[9] =
{
  {
    "actionId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, actionid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "actionType",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, has_actiontype),
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, actiontype),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "opusId",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, opusid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userInfo",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, userinfo),
    &game__pbuser_basic_info__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, has_createdate),
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, createdate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sourceAction",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, sourceaction),
    &game__pbopus_action__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commentAction",
    51,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, commentaction),
    &game__pbaction_comment__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flowerAction",
    52,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, floweraction),
    &game__pbaction_flower__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "guessAction",
    53,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBOpusAction, guessaction),
    &game__pbaction_guess__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbopus_action__field_indices_by_name[] = {
  0,   /* field[0] = actionId */
  1,   /* field[1] = actionType */
  6,   /* field[6] = commentAction */
  4,   /* field[4] = createDate */
  7,   /* field[7] = flowerAction */
  8,   /* field[8] = guessAction */
  2,   /* field[2] = opusId */
  5,   /* field[5] = sourceAction */
  3,   /* field[3] = userInfo */
};
static const ProtobufCIntRange game__pbopus_action__number_ranges[5 + 1] =
{
  { 1, 0 },
  { 5, 2 },
  { 11, 4 },
  { 15, 5 },
  { 51, 6 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor game__pbopus_action__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBOpusAction",
  "PBOpusAction",
  "Game__PBOpusAction",
  "game",
  sizeof(Game__PBOpusAction),
  9,
  game__pbopus_action__field_descriptors,
  game__pbopus_action__field_indices_by_name,
  5,  game__pbopus_action__number_ranges,
  (ProtobufCMessageInit) game__pbopus_action__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbaction_comment__field_descriptors[1] =
{
  {
    "content",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBActionComment, content),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbaction_comment__field_indices_by_name[] = {
  0,   /* field[0] = content */
};
static const ProtobufCIntRange game__pbaction_comment__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor game__pbaction_comment__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBActionComment",
  "PBActionComment",
  "Game__PBActionComment",
  "game",
  sizeof(Game__PBActionComment),
  1,
  game__pbaction_comment__field_descriptors,
  game__pbaction_comment__field_indices_by_name,
  1,  game__pbaction_comment__number_ranges,
  (ProtobufCMessageInit) game__pbaction_comment__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbaction_flower__field_descriptors[1] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBActionFlower, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbaction_flower__field_indices_by_name[] = {
  0,   /* field[0] = type */
};
static const ProtobufCIntRange game__pbaction_flower__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor game__pbaction_flower__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBActionFlower",
  "PBActionFlower",
  "Game__PBActionFlower",
  "game",
  sizeof(Game__PBActionFlower),
  1,
  game__pbaction_flower__field_descriptors,
  game__pbaction_flower__field_indices_by_name,
  1,  game__pbaction_flower__number_ranges,
  (ProtobufCMessageInit) game__pbaction_flower__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbaction_guess__field_descriptors[2] =
{
  {
    "words",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Game__PBActionGuess, n_words),
    PROTOBUF_C_OFFSETOF(Game__PBActionGuess, words),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "correct",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    PROTOBUF_C_OFFSETOF(Game__PBActionGuess, has_correct),
    PROTOBUF_C_OFFSETOF(Game__PBActionGuess, correct),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbaction_guess__field_indices_by_name[] = {
  1,   /* field[1] = correct */
  0,   /* field[0] = words */
};
static const ProtobufCIntRange game__pbaction_guess__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__pbaction_guess__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBActionGuess",
  "PBActionGuess",
  "Game__PBActionGuess",
  "game",
  sizeof(Game__PBActionGuess),
  2,
  game__pbaction_guess__field_descriptors,
  game__pbaction_guess__field_indices_by_name,
  1,  game__pbaction_guess__number_ranges,
  (ProtobufCMessageInit) game__pbaction_guess__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t game__pbaction_times__value__default_value = 0;
static const ProtobufCFieldDescriptor game__pbaction_times__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBActionTimes, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBActionTimes, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBActionTimes, has_value),
    PROTOBUF_C_OFFSETOF(Game__PBActionTimes, value),
    NULL,
    &game__pbaction_times__value__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbaction_times__field_indices_by_name[] = {
  1,   /* field[1] = name */
  0,   /* field[0] = type */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange game__pbaction_times__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor game__pbaction_times__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBActionTimes",
  "PBActionTimes",
  "Game__PBActionTimes",
  "game",
  sizeof(Game__PBActionTimes),
  3,
  game__pbaction_times__field_descriptors,
  game__pbaction_times__field_indices_by_name,
  1,  game__pbaction_times__number_ranges,
  (ProtobufCMessageInit) game__pbaction_times__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbtimeline__field_descriptors[2] =
{
  {
    "opus",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBTimeline, opus),
    &game__pbopus__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "action",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBTimeline, action),
    &game__pbopus_action__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbtimeline__field_indices_by_name[] = {
  1,   /* field[1] = action */
  0,   /* field[0] = opus */
};
static const ProtobufCIntRange game__pbtimeline__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__pbtimeline__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBTimeline",
  "PBTimeline",
  "Game__PBTimeline",
  "game",
  sizeof(Game__PBTimeline),
  2,
  game__pbtimeline__field_descriptors,
  game__pbtimeline__field_indices_by_name,
  1,  game__pbtimeline__number_ranges,
  (ProtobufCMessageInit) game__pbtimeline__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue game__pbopus_aim__enum_values_by_number[13] =
{
  { "UNKNOWN", "GAME__PBOPUS_AIM__UNKNOWN", 0 },
  { "DRAW", "GAME__PBOPUS_AIM__DRAW", 1 },
  { "GUESS", "GAME__PBOPUS_AIM__GUESS", 2 },
  { "COMMENT", "GAME__PBOPUS_AIM__COMMENT", 3 },
  { "REPOST", "GAME__PBOPUS_AIM__REPOST", 4 },
  { "DRAW_TO_USER", "GAME__PBOPUS_AIM__DRAW_TO_USER", 5 },
  { "FLOWER", "GAME__PBOPUS_AIM__FLOWER", 6 },
  { "TOMATO", "GAME__PBOPUS_AIM__TOMATO", 7 },
  { "ONLY_COMMENT", "GAME__PBOPUS_AIM__ONLY_COMMENT", 8 },
  { "DRAW_CONTEST", "GAME__PBOPUS_AIM__DRAW_CONTEST", 9 },
  { "SING", "GAME__PBOPUS_AIM__SING", 1000 },
  { "SING_TO_USER", "GAME__PBOPUS_AIM__SING_TO_USER", 1001 },
  { "SING_CONTEST", "GAME__PBOPUS_AIM__SING_CONTEST", 1002 },
};
static const ProtobufCIntRange game__pbopus_aim__value_ranges[] = {
{0, 0},{1000, 10},{0, 13}
};
const ProtobufCEnumValueIndex game__pbopus_aim__enum_values_by_name[13] =
{
  { "COMMENT", 3 },
  { "DRAW", 1 },
  { "DRAW_CONTEST", 9 },
  { "DRAW_TO_USER", 5 },
  { "FLOWER", 6 },
  { "GUESS", 2 },
  { "ONLY_COMMENT", 8 },
  { "REPOST", 4 },
  { "SING", 10 },
  { "SING_CONTEST", 12 },
  { "SING_TO_USER", 11 },
  { "TOMATO", 7 },
  { "UNKNOWN", 0 },
};
const ProtobufCEnumDescriptor game__pbopus_aim__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "game.PBOpusAim",
  "PBOpusAim",
  "Game__PBOpusAim",
  "game",
  13,
  game__pbopus_aim__enum_values_by_number,
  13,
  game__pbopus_aim__enum_values_by_name,
  2,
  game__pbopus_aim__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
