/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Photo.proto */

#ifndef PROTOBUF_C_Photo_2eproto__INCLUDED
#define PROTOBUF_C_Photo_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "GameBasic.pb-c.h"

typedef struct _Game__PBUserPhoto Game__PBUserPhoto;
typedef struct _Game__PBUserPhotoList Game__PBUserPhotoList;


/* --- enums --- */

typedef enum _Game__PBPhotoUsage {
  GAME__PBPHOTO_USAGE__BEGIN = 0,
  /*
   * 用于临摹
   */
  GAME__PBPHOTO_USAGE__FOR_DRAW = 1,
  /*
   * 用于PS素材
   */
  GAME__PBPHOTO_USAGE__FOR_PS = 2,
  GAME__PBPHOTO_USAGE__END = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GAME__PBPHOTO_USAGE)
} Game__PBPhotoUsage;

/* --- messages --- */

struct  _Game__PBUserPhoto
{
  ProtobufCMessage base;
  char *userid;
  /*
   * useless for client
   */
  char *photoid;
  /*
   * used for update and delete
   */
  char *userphotoid;
  char *url;
  char *name;
  protobuf_c_boolean has_createdate;
  int32_t createdate;
  size_t n_tags;
  char **tags;
  /*
   * refer to PBPhotoUsage
   */
  protobuf_c_boolean has_usage;
  int32_t usage;
  /*
   * photo width
   */
  protobuf_c_boolean has_width;
  float width;
  /*
   * photo height
   */
  protobuf_c_boolean has_height;
  float height;
};
#define GAME__PBUSER_PHOTO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_photo__descriptor) \
    , NULL, NULL, NULL, NULL, NULL, 0,0, 0,NULL, 0,0, 0,0, 0,0 }


struct  _Game__PBUserPhotoList
{
  ProtobufCMessage base;
  char *userid;
  size_t n_photolist;
  Game__PBUserPhoto **photolist;
};
#define GAME__PBUSER_PHOTO_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbuser_photo_list__descriptor) \
    , NULL, 0,NULL }


/* Game__PBUserPhoto methods */
void   game__pbuser_photo__init
                     (Game__PBUserPhoto         *message);
size_t game__pbuser_photo__get_packed_size
                     (const Game__PBUserPhoto   *message);
size_t game__pbuser_photo__pack
                     (const Game__PBUserPhoto   *message,
                      uint8_t             *out);
size_t game__pbuser_photo__pack_to_buffer
                     (const Game__PBUserPhoto   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserPhoto *
       game__pbuser_photo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_photo__free_unpacked
                     (Game__PBUserPhoto *message,
                      ProtobufCAllocator *allocator);
/* Game__PBUserPhotoList methods */
void   game__pbuser_photo_list__init
                     (Game__PBUserPhotoList         *message);
size_t game__pbuser_photo_list__get_packed_size
                     (const Game__PBUserPhotoList   *message);
size_t game__pbuser_photo_list__pack
                     (const Game__PBUserPhotoList   *message,
                      uint8_t             *out);
size_t game__pbuser_photo_list__pack_to_buffer
                     (const Game__PBUserPhotoList   *message,
                      ProtobufCBuffer     *buffer);
Game__PBUserPhotoList *
       game__pbuser_photo_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbuser_photo_list__free_unpacked
                     (Game__PBUserPhotoList *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__PBUserPhoto_Closure)
                 (const Game__PBUserPhoto *message,
                  void *closure_data);
typedef void (*Game__PBUserPhotoList_Closure)
                 (const Game__PBUserPhotoList *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    game__pbphoto_usage__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_photo__descriptor;
extern const ProtobufCMessageDescriptor game__pbuser_photo_list__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Photo_2eproto__INCLUDED */
