/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "Photo.pb-c.h"
void   game__pbuser_photo__init
                     (Game__PBUserPhoto         *message)
{
  static Game__PBUserPhoto init_value = GAME__PBUSER_PHOTO__INIT;
  *message = init_value;
}
size_t game__pbuser_photo__get_packed_size
                     (const Game__PBUserPhoto *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbuser_photo__pack
                     (const Game__PBUserPhoto *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbuser_photo__pack_to_buffer
                     (const Game__PBUserPhoto *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBUserPhoto *
       game__pbuser_photo__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBUserPhoto *)
     protobuf_c_message_unpack (&game__pbuser_photo__descriptor,
                                allocator, len, data);
}
void   game__pbuser_photo__free_unpacked
                     (Game__PBUserPhoto *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   game__pbuser_photo_list__init
                     (Game__PBUserPhotoList         *message)
{
  static Game__PBUserPhotoList init_value = GAME__PBUSER_PHOTO_LIST__INIT;
  *message = init_value;
}
size_t game__pbuser_photo_list__get_packed_size
                     (const Game__PBUserPhotoList *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t game__pbuser_photo_list__pack
                     (const Game__PBUserPhotoList *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t game__pbuser_photo_list__pack_to_buffer
                     (const Game__PBUserPhotoList *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Game__PBUserPhotoList *
       game__pbuser_photo_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Game__PBUserPhotoList *)
     protobuf_c_message_unpack (&game__pbuser_photo_list__descriptor,
                                allocator, len, data);
}
void   game__pbuser_photo_list__free_unpacked
                     (Game__PBUserPhotoList *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &game__pbuser_photo_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor game__pbuser_photo__field_descriptors[10] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "photoId",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, photoid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "userPhotoId",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, userphotoid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "url",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, url),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, name),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "createDate",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, has_createdate),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, createdate),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tags",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, n_tags),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, tags),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "usage",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, has_usage),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, usage),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, has_width),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, width),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, has_height),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhoto, height),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbuser_photo__field_indices_by_name[] = {
  5,   /* field[5] = createDate */
  9,   /* field[9] = height */
  4,   /* field[4] = name */
  1,   /* field[1] = photoId */
  6,   /* field[6] = tags */
  3,   /* field[3] = url */
  7,   /* field[7] = usage */
  0,   /* field[0] = userId */
  2,   /* field[2] = userPhotoId */
  8,   /* field[8] = width */
};
static const ProtobufCIntRange game__pbuser_photo__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor game__pbuser_photo__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBUserPhoto",
  "PBUserPhoto",
  "Game__PBUserPhoto",
  "game",
  sizeof(Game__PBUserPhoto),
  10,
  game__pbuser_photo__field_descriptors,
  game__pbuser_photo__field_indices_by_name,
  1,  game__pbuser_photo__number_ranges,
  (ProtobufCMessageInit) game__pbuser_photo__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor game__pbuser_photo_list__field_descriptors[2] =
{
  {
    "userId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(Game__PBUserPhotoList, userid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "photoList",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    PROTOBUF_C_OFFSETOF(Game__PBUserPhotoList, n_photolist),
    PROTOBUF_C_OFFSETOF(Game__PBUserPhotoList, photolist),
    &game__pbuser_photo__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned game__pbuser_photo_list__field_indices_by_name[] = {
  1,   /* field[1] = photoList */
  0,   /* field[0] = userId */
};
static const ProtobufCIntRange game__pbuser_photo_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor game__pbuser_photo_list__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "game.PBUserPhotoList",
  "PBUserPhotoList",
  "Game__PBUserPhotoList",
  "game",
  sizeof(Game__PBUserPhotoList),
  2,
  game__pbuser_photo_list__field_descriptors,
  game__pbuser_photo_list__field_indices_by_name,
  1,  game__pbuser_photo_list__number_ranges,
  (ProtobufCMessageInit) game__pbuser_photo_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue game__pbphoto_usage__enum_values_by_number[4] =
{
  { "BEGIN", "GAME__PBPHOTO_USAGE__BEGIN", 0 },
  { "FOR_DRAW", "GAME__PBPHOTO_USAGE__FOR_DRAW", 1 },
  { "FOR_PS", "GAME__PBPHOTO_USAGE__FOR_PS", 2 },
  { "END", "GAME__PBPHOTO_USAGE__END", 3 },
};
static const ProtobufCIntRange game__pbphoto_usage__value_ranges[] = {
{0, 0},{0, 4}
};
const ProtobufCEnumValueIndex game__pbphoto_usage__enum_values_by_name[4] =
{
  { "BEGIN", 0 },
  { "END", 3 },
  { "FOR_DRAW", 1 },
  { "FOR_PS", 2 },
};
const ProtobufCEnumDescriptor game__pbphoto_usage__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "game.PBPhotoUsage",
  "PBPhotoUsage",
  "Game__PBPhotoUsage",
  "game",
  4,
  game__pbphoto_usage__enum_values_by_number,
  4,
  game__pbphoto_usage__enum_values_by_name,
  1,
  game__pbphoto_usage__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
