/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_Sing_2eproto__INCLUDED
#define PROTOBUF_C_Sing_2eproto__INCLUDED

#import "protobuf-c.h"

PROTOBUF_C_BEGIN_DECLS


typedef struct _Game__PBSong Game__PBSong;
typedef struct _Game__PBSongList Game__PBSongList;
typedef struct _Game__PBSingOpus Game__PBSingOpus;


/* --- enums --- */

typedef enum _Game__PBVoiceType {
  GAME__PBVOICE_TYPE__VoiceTypeOrigin = 0,
  GAME__PBVOICE_TYPE__VoiceTypeTomCat = 1,
  GAME__PBVOICE_TYPE__VoiceTypeDuck = 2,
  GAME__PBVOICE_TYPE__VoiceTypeMale = 3,
  GAME__PBVOICE_TYPE__VoiceTypeChild = 4,
  GAME__PBVOICE_TYPE__VoiceTypeFemale = 5
} Game__PBVoiceType;

/* --- messages --- */

struct  _Game__PBSong
{
  ProtobufCMessage base;
  char *songid;
  char *name;
  char *author;
  char *lyric;
  size_t n_tag;
  int32_t *tag;
};
#define GAME__PBSONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsong__descriptor) \
    , NULL, NULL, NULL, NULL, 0,NULL }


struct  _Game__PBSongList
{
  ProtobufCMessage base;
  size_t n_songs;
  Game__PBSong **songs;
};
#define GAME__PBSONG_LIST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsong_list__descriptor) \
    , 0,NULL }


struct  _Game__PBSingOpus
{
  ProtobufCMessage base;
  Game__PBSong *song;
  protobuf_c_boolean has_voicetype;
  Game__PBVoiceType voicetype;
  protobuf_c_boolean has_duration;
  float duration;
  protobuf_c_boolean has_pitch;
  float pitch;
};
#define GAME__PBSING_OPUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&game__pbsing_opus__descriptor) \
    , NULL, 0,0, 0,1, 0,1 }


/* Game__PBSong methods */
void   game__pbsong__init
                     (Game__PBSong         *message);
size_t game__pbsong__get_packed_size
                     (const Game__PBSong   *message);
size_t game__pbsong__pack
                     (const Game__PBSong   *message,
                      uint8_t             *out);
size_t game__pbsong__pack_to_buffer
                     (const Game__PBSong   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSong *
       game__pbsong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsong__free_unpacked
                     (Game__PBSong *message,
                      ProtobufCAllocator *allocator);
/* Game__PBSongList methods */
void   game__pbsong_list__init
                     (Game__PBSongList         *message);
size_t game__pbsong_list__get_packed_size
                     (const Game__PBSongList   *message);
size_t game__pbsong_list__pack
                     (const Game__PBSongList   *message,
                      uint8_t             *out);
size_t game__pbsong_list__pack_to_buffer
                     (const Game__PBSongList   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSongList *
       game__pbsong_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsong_list__free_unpacked
                     (Game__PBSongList *message,
                      ProtobufCAllocator *allocator);
/* Game__PBSingOpus methods */
void   game__pbsing_opus__init
                     (Game__PBSingOpus         *message);
size_t game__pbsing_opus__get_packed_size
                     (const Game__PBSingOpus   *message);
size_t game__pbsing_opus__pack
                     (const Game__PBSingOpus   *message,
                      uint8_t             *out);
size_t game__pbsing_opus__pack_to_buffer
                     (const Game__PBSingOpus   *message,
                      ProtobufCBuffer     *buffer);
Game__PBSingOpus *
       game__pbsing_opus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   game__pbsing_opus__free_unpacked
                     (Game__PBSingOpus *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Game__PBSong_Closure)
                 (const Game__PBSong *message,
                  void *closure_data);
typedef void (*Game__PBSongList_Closure)
                 (const Game__PBSongList *message,
                  void *closure_data);
typedef void (*Game__PBSingOpus_Closure)
                 (const Game__PBSingOpus *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    game__pbvoice_type__descriptor;
extern const ProtobufCMessageDescriptor game__pbsong__descriptor;
extern const ProtobufCMessageDescriptor game__pbsong_list__descriptor;
extern const ProtobufCMessageDescriptor game__pbsing_opus__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_Sing_2eproto__INCLUDED */
