//
//  NotificationName.h
//  Draw
//
//  Created by 小涛 王 on 12-7-30.
//  Copyright (c) 2012年 甘橙软件. All rights reserved.
//

#ifndef Draw_NotificationName_h
#define Draw_NotificationName_h

#define NOTIFICATION_JOIN_GAME_RESPONSE         @"NOTIFICATION_JOIN_GAME_RESPONSE"
#define NOTIFICATION_ENTER_ROOM_RESPONSE        @"NOTIFICATION_ENTER_ROOM_RESPONSE"
#define NOTIFICAIION_CREATE_ROOM_RESPONSE       @"NOTIFICAIION_CREATE_ROOM_RESPONSE"
#define NOTIFICAIION_GET_ROOMS_RESPONSE         @"NOTIFICAIION_GET_ROOMS_RESPONSE"
#define NOTIFICATION_ROOM                       @"NOTIFICATION_ROOM"
#define NOTIFICAIION_CHAT_REQUEST               @"NOTIFICAIION_CHAT_REQUEST"

#define NOTIFICATION_GAME_START_NOTIFICATION_REQUEST @"NOTIFICATION_GAME_START_NOTIFICATION_REQUEST"
#define NOTIFICATION_GAME_OVER_NOTIFICATION_REQUEST @"NOTIFICATION_GAME_OVER_NOTIFICATION_REQUEST"

#define NOTIFICATION_NEXT_PLAYER_START          @"NOTIFICATION_NEXT_PLAYER_START"

#define NOTIFICATION_NETWORK_CONNECTED          @"NOTIFICATION_NETWORK_CONNECTED"
#define NOTIFICATION_NETWORK_DISCONNECTED       @"NOTIFICATION_NETWORK_DISCONNECTED"

#define ROOMS_DID_UPDATE @"ROOM_DID_UPDATE" 

#define NOTIFICATION_BALANCE_UPDATED            @"NOTIFICATION_BALANCE_UPDATED"

#define NOTIFICATION_ALIPAY_PAY_CALLBACK        @"NOTIFICATION_ALIPAY_PAY_CALLBACK"


#endif
