//
// JsonModel.m
//
// Json Mapping Automatically Generated By JsonToolkit Library for Objective C
// Diego Trinciarelli 2011
//

#import "AppTask.h"

@implementation AppTask

- (void) dealloc
{
    [_appid release];
    [_name release];
    [_url release];
    [_desc release];
    [_schema release];
    [super dealloc];
}

+ (id) objectWithDictionary:(NSDictionary*)dictionary
{
    id obj = [[[AppTask alloc] initWithDictionary:dictionary] autorelease];
    return obj;
}

- (id) initWithDictionary:(NSDictionary*)dictionary
{
    self=[super init];
    if(self)
    {
        @try {
            self.index = [[dictionary objectForKey:@"index"] intValue];
            self.appid = [dictionary objectForKey:@"appid"];
            self.name = [dictionary objectForKey:@"name"];
            self.url = [dictionary objectForKey:@"url"];
            self.desc = [dictionary objectForKey:@"desc"];
            self.award = [[dictionary objectForKey:@"award"] intValue];
            self.schema = [dictionary objectForKey:@"schema"];
            self.show = [[dictionary objectForKey:@"show"] intValue];
            self.type = [[dictionary objectForKey:@"type"] intValue];
            self.wallType = [[dictionary objectForKey:@"wall_type"] intValue];
        }
        @catch (NSException *exception) {
            PPDebug(@"<initWithDictionary> catch exception=%@", [exception description]);
        }
        @finally {
        }

    }
    return self;
}

- (NSString*)appAwardKey
{
    return [NSString stringWithFormat:@"KEY_APP_TASK_AWARD_%@", self.appid];
}

- (BOOL)isAppAward
{
    NSUserDefaults* ud = [NSUserDefaults standardUserDefaults];
    return [ud boolForKey:[self appAwardKey]];
}

- (void)setAppAward
{
    NSUserDefaults* ud = [NSUserDefaults standardUserDefaults];
    [ud setBool:YES forKey:[self appAwardKey]];
    [ud synchronize];
}



@end

//JsonModel.m End
